import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from 'next/font/google'
import { Toaster } from "sonner";
import { Providers } from "./providers";
import { authSession } from "@/lib/auth-utils";

const dmSans = DM_Sans({
  subsets: ['latin']
}) 

export const metadata: Metadata = {
  title: "VivaCrochet",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await authSession()
  const userId = session?.user.id
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <Providers userId={userId}>{children}</Providers>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
